// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using R.DAL.Contexts;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221216084926_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DAL.Models.Candidate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Level")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Stack")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Сandidates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Level = "Junior Strong",
                            Name = "Dmytro",
                            Stack = ".Net",
                            Surname = "Melnyk"
                        },
                        new
                        {
                            Id = 2,
                            Level = "Junior",
                            Name = "Slavko",
                            Stack = "Js, React",
                            Surname = "Zozuk"
                        },
                        new
                        {
                            Id = 3,
                            Level = "Middle",
                            Name = "Liubomyr",
                            Stack = "NodeJs",
                            Surname = "Liuklian"
                        });
                });

            modelBuilder.Entity("DAL.Models.Interview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CandidatId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("InterviewerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CandidatId");

                    b.HasIndex("InterviewerId");

                    b.ToTable("Interviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CandidatId = 1,
                            EndDate = new DateTime(2022, 12, 25, 11, 30, 0, 0, DateTimeKind.Unspecified),
                            InterviewerId = 1,
                            StartDate = new DateTime(2022, 12, 25, 10, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            CandidatId = 2,
                            EndDate = new DateTime(2022, 12, 20, 13, 30, 0, 0, DateTimeKind.Unspecified),
                            InterviewerId = 2,
                            StartDate = new DateTime(2022, 12, 20, 12, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            CandidatId = 3,
                            EndDate = new DateTime(2022, 12, 22, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            InterviewerId = 2,
                            StartDate = new DateTime(2022, 12, 22, 15, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("DAL.Models.Interviewer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Level")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Stack")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Interviewers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Level = "TL",
                            Name = "Taras",
                            Stack = ".Net",
                            Surname = "Shevchenko"
                        },
                        new
                        {
                            Id = 2,
                            Level = "Senior Strong Architector",
                            Name = "Nazar",
                            Stack = "Js",
                            Surname = "Leshnevskiy"
                        });
                });

            modelBuilder.Entity("DAL.Models.Interview", b =>
                {
                    b.HasOne("DAL.Models.Candidate", "Candidat")
                        .WithMany()
                        .HasForeignKey("CandidatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Models.Interviewer", "Interviewer")
                        .WithMany()
                        .HasForeignKey("InterviewerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidat");

                    b.Navigation("Interviewer");
                });
#pragma warning restore 612, 618
        }
    }
}
